// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VirtualEventTicketingSystem.Models;

#nullable disable

namespace VirtualEventTicketingSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251204194452_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VirtualEventTicketingSystem.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Online educational sessions",
                            Name = "Webinar"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Live musical performances",
                            Name = "Concert"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Interactive training sessions",
                            Name = "Workshop"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Professional Meetings",
                            Name = "Conference"
                        });
                });

            modelBuilder.Entity("VirtualEventTicketingSystem.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableTickets = 10,
                            CategoryId = 1,
                            DateTime = new DateTime(2025, 2, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 15.99m,
                            Title = "C# Fundamentals"
                        },
                        new
                        {
                            Id = 2,
                            AvailableTickets = 3,
                            CategoryId = 2,
                            DateTime = new DateTime(2025, 2, 20, 19, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 30.00m,
                            Title = "Rock Night Live"
                        },
                        new
                        {
                            Id = 3,
                            AvailableTickets = 8,
                            CategoryId = 3,
                            DateTime = new DateTime(2025, 2, 25, 14, 0, 0, 0, DateTimeKind.Utc),
                            TicketPrice = 25.50m,
                            Title = "UI/UX Workshop"
                        });
                });

            modelBuilder.Entity("VirtualEventTicketingSystem.Models.EventPurchase", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("EventId", "PurchaseId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("EventPurchases");
                });

            modelBuilder.Entity("VirtualEventTicketingSystem.Models.Purchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PurchaseId"));

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric");

                    b.HasKey("PurchaseId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("VirtualEventTicketingSystem.Models.Event", b =>
                {
                    b.HasOne("VirtualEventTicketingSystem.Models.Category", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VirtualEventTicketingSystem.Models.EventPurchase", b =>
                {
                    b.HasOne("VirtualEventTicketingSystem.Models.Event", "Event")
                        .WithMany("EventPurchases")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirtualEventTicketingSystem.Models.Purchase", "Purchase")
                        .WithMany("EventPurchases")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("VirtualEventTicketingSystem.Models.Category", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("VirtualEventTicketingSystem.Models.Event", b =>
                {
                    b.Navigation("EventPurchases");
                });

            modelBuilder.Entity("VirtualEventTicketingSystem.Models.Purchase", b =>
                {
                    b.Navigation("EventPurchases");
                });
#pragma warning restore 612, 618
        }
    }
}
